export const teamMembers = [
  {
    id: 1,
    name: "Alex Johnson",
    role: "Team Lead",
    image: "/young-creative-professional-portrait.jpg",
    bio: "Passionate about digital design and user experience",
  },
  {
    id: 2,
    name: "Maria Garcia",
    role: "Community Manager",
    image: "/friendly-community-manager-portrait.jpg",
    bio: "Dedicated to building an inclusive creative community",
  },
  {
    id: 3,
    name: "James Wilson",
    role: "Tech Lead",
    image: "/tech-enthusiast-developer-portrait.jpg",
    bio: "Expert in web technologies and creative coding",
  },
  {
    id: 4,
    name: "Sarah Chen",
    role: "Design Director",
    image: "/graphic-designer-creative-portrait.jpg",
    bio: "Innovative designer pushing creative boundaries",
  },
  {
    id: 5,
    name: "Michael Brown",
    role: "Events Coordinator",
    image: "/event-organizer-professional-portrait.jpg",
    bio: "Making memorable events for our community",
  },
]

export const facultyMembers = [
  {
    id: 1,
    name: "Dr. Rajesh Kumar",
    role: "Faculty Advisor",
    expertise: "Digital Arts",
    image: "/faculty-academic-mentor-portrait.jpg",
    email: "r.kumar@university.edu",
  },
  {
    id: 2,
    name: "Prof. Amelia Zhang",
    role: "Technology Mentor",
    expertise: "Web Development",
    image: "/faculty-technology-advisor-portrait.jpg",
    email: "a.zhang@university.edu",
  },
  {
    id: 3,
    name: "Dr. Michael O'Brien",
    role: "Creative Director",
    expertise: "Design Thinking",
    image: "/faculty-creative-director-portrait.jpg",
    email: "m.obrien@university.edu",
  },
  {
    id: 4,
    name: "Prof. Priya Patel",
    role: "Events Coordinator",
    expertise: "Event Management",
    image: "/faculty-event-planning-portrait.jpg",
    email: "p.patel@university.edu",
  },
]

export const upcomingEvents = [
  {
    id: 1,
    title: "Creative Workshop Series",
    category: "workshop",
    date: "2025-02-15",
    time: "2:00 PM",
    location: "Arts Building, Room 101",
    description:
      "Join us for an interactive workshop on digital illustration techniques. Learn from industry professionals and create your own artwork.",
    image: "/creative-workshop-event.jpg",
    attendees: 45,
    isFeatured: true,
  },
  {
    id: 2,
    title: "Art Exhibition Opening",
    category: "exhibition",
    date: "2025-02-20",
    time: "6:00 PM",
    location: "Campus Gallery",
    description:
      "Celebrate student artwork and creative projects in our annual gallery exhibition featuring works from all club members.",
    image: "/art-exhibition-gallery.png",
    attendees: 120,
    isFeatured: true,
  },
  {
    id: 3,
    title: "Team Building Outing",
    category: "social",
    date: "2025-02-25",
    time: "10:00 AM",
    location: "Central Park",
    description:
      "An outdoor team building event where we explore nature, play games, and strengthen our community bonds.",
    image: "/outdoor-team-building.png",
    attendees: 60,
    isFeatured: false,
  },
  {
    id: 4,
    title: "Photography Masterclass",
    category: "workshop",
    date: "2025-03-05",
    time: "3:00 PM",
    location: "Studio A",
    description:
      "Learn professional photography techniques including composition, lighting, and post-processing from expert photographers.",
    image: "/photography-workshop-class.jpg",
    attendees: 35,
    isFeatured: false,
  },
  {
    id: 5,
    title: "Cultural Performance Night",
    category: "performance",
    date: "2025-03-12",
    time: "7:00 PM",
    location: "Main Auditorium",
    description:
      "Experience diverse cultural performances including music, dance, and theater from our talented community members.",
    image: "/cultural-performance-stage-event.jpg",
    attendees: 200,
    isFeatured: true,
  },
  {
    id: 6,
    title: "Networking Dinner",
    category: "social",
    date: "2025-03-18",
    time: "6:30 PM",
    location: "Grand Ballroom",
    description:
      "Connect with fellow creative minds over an elegant dinner while sharing ideas and building lasting friendships.",
    image: "/elegant-dinner-celebration-event.jpg",
    attendees: 85,
    isFeatured: false,
  },
  {
    id: 7,
    title: "Design Competition",
    category: "competition",
    date: "2025-03-25",
    time: "1:00 PM",
    location: "Competition Hall",
    description:
      "Showcase your design skills in our annual competition with prizes, recognition, and networking opportunities.",
    image: "/design-competition-showcase.jpg",
    attendees: 100,
    isFeatured: false,
  },
  {
    id: 8,
    title: "Charity Fundraiser",
    category: "social",
    date: "2025-04-05",
    time: "5:00 PM",
    location: "Community Center",
    description:
      "Help us make a difference! Join our charity fundraiser event with entertainment, food, and fun activities.",
    image: "/charity-fundraiser-community-event.jpg",
    attendees: 150,
    isFeatured: false,
  },
]

export const galleryImages = [
  {
    id: 1,
    title: "Creative Workshop",
    category: "workshops",
    image: "/creative-workshop-event.jpg",
    date: "2025-01-20",
  },
  {
    id: 2,
    title: "Art Exhibition",
    category: "exhibitions",
    image: "/art-exhibition-gallery.png",
    date: "2025-01-25",
  },
  {
    id: 3,
    title: "Outdoor Event",
    category: "social",
    image: "/outdoor-team-building.png",
    date: "2025-02-01",
  },
  {
    id: 4,
    title: "Photography Class",
    category: "workshops",
    image: "/photography-workshop-class.jpg",
    date: "2025-02-10",
  },
  {
    id: 5,
    title: "Performance",
    category: "performances",
    image: "/cultural-performance-stage-event.jpg",
    date: "2025-02-15",
  },
  {
    id: 6,
    title: "Dinner Event",
    category: "social",
    image: "/elegant-dinner-celebration-event.jpg",
    date: "2025-02-20",
  },
  {
    id: 7,
    title: "Competition",
    category: "competitions",
    image: "/design-competition-showcase.jpg",
    date: "2025-02-28",
  },
  {
    id: 8,
    title: "Fundraiser",
    category: "social",
    image: "/charity-fundraiser-community-event.jpg",
    date: "2025-03-05",
  },
]
